### ISSUE TITLE
error on sensi.start

### ISSUE THREAD

**Issue by kevin-devicebook** [mguterl/sensi#2]
get this error when calling sensi.start:

 Unhandled rejection Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at TLSSocket.socketOnEnd (_http_client.js:423:23)
    at emitNone (events.js:111:20)
    at TLSSocket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)

maybe sensi has deprecated or changed the API this was written against?

**Comment by kskenyon** [comment]
The API was eliminated in 2018.
